CREATE DATABASE ElilusDB
GO
USE ElilusDB

CREATE TABLE USUARIO(
	ID_USUARIO INT IDENTITY(1,1),
	NOME NVARCHAR(50) NOT NULL,
	SOBRENOME NVARCHAR(50),
	TELEFONE NVARCHAR(14),
	EMAIL NVARCHAR(50)NOT NULL,
	SENHA NVARCHAR(50) NOT NULL
	CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO),
);

CREATE TABLE PRODUTO_CATEGORIA(
	ID_PROD_CATEGORIA INT IDENTITY(1,1),
	DESCRICAO NVARCHAR(250),
	CONSTRAINT PK_PROD_CATEGORIA PRIMARY KEY(ID_PROD_CATEGORIA)
);

CREATE TABLE PRODUTO(
	ID_PRODUTO INT IDENTITY(1,1),
	ID_PROD_CATEGORIA INT,
	PATH_IMAGEM NVARCHAR(500),
	DESCRICAO NVARCHAR(250),
	CONSTRAINT PK_PRODUTO PRIMARY KEY(ID_PRODUTO),
	CONSTRAINT FK_PROD_CATEGORIA FOREIGN KEY (ID_PROD_CATEGORIA) REFERENCES PRODUTO_CATEGORIA(ID_PROD_CATEGORIA)
);

CREATE TABLE USUARIO_FAVORITO(
	ID_USER_FAV INT IDENTITY(1,1),
	ID_PRODUTO INT,
	ID_USUARIO INT,
	CONSTRAINT PK_USER_FAVORITO PRIMARY KEY(ID_USER_FAV),
	CONSTRAINT FK_FAV_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
	CONSTRAINT FK_FAV_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

