CREATE DATABASE ElilusDB;
USE ElilusDB;
CREATE TABLE USUARIO(
	ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(50),
	TELEFONE VARCHAR(14),
	EMAIL VARCHAR(50)NOT NULL,
	SENHA VARCHAR(50) NOT NULL
);
CREATE TABLE PRODUTO_CATEGORIA(
	ID_PROD_CATEGORIA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	DESCRICAO NVARCHAR(250)
);
CREATE TABLE PRODUTO(
	ID_PRODUTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_PROD_CATEGORIA INT,
	PATH_IMAGEM NVARCHAR(500),
	DESCRICAO NVARCHAR(250),
	CONSTRAINT FK_PROD_CATEGORIA FOREIGN KEY (ID_PROD_CATEGORIA) REFERENCES PRODUTO_CATEGORIA(ID_PROD_CATEGORIA)
);
CREATE TABLE USUARIO_FAVORITO(
	ID_USER_FAV INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID_PRODUTO INT,
	ID_USUARIO INT,
	CONSTRAINT FK_FAV_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
	CONSTRAINT FK_FAV_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
Commit;